buildkite: enable linting of configuration YAML files
Uses yamllint to check configuration files for typical issues and
inconsistencies.

diff --git a/.buildkite/lint b/.buildkite/lint
--- a/.buildkite/lint
+++ b/.buildkite/lint
@@ -278,6 +278,23 @@ check_gitlint ()
 	rm -f gitlint-*.txt
 }
 
+check_yamllint()
+{
+	YAMLLINT_ERROR=0
+	YAMLLINT_OUTPUT=$(yamllint -s -f colored cfg/config.yaml cfg/conf.d/) || YAMLLINT_ERROR=$?
+	if [ $YAMLLINT_ERROR -ne 0 ]; then
+		# Print error to log
+		>&2 cat <<< $YAMLLINT_OUTPUT
+
+		{
+			echo "<h4>Detected yamllint Errors</h4>"
+			echo '<code><pre class="term">'
+			echo -e $YAMLLINT_OUTPUT
+			echo '</pre></code>'
+		} | buildkite-agent annotate --context yamllint --style error
+		exit $YAMLLINT_ERROR
+	fi
+}
 
 ### Main Program
 
@@ -293,6 +310,8 @@ check_commit_authors
 echo "-> Running gitlint to check commit messages"
 check_gitlint
 
+echo "-> Running yamllint on configuration files"
+check_yamllint
+
 echo "-> Running 'make check'"
 gmake check
-
