buildkite: improve gitlint error annotation
Nicely represent gitlint failures as a buildkite annotation so it is
easier to spot.

diff --git a/.buildkite/lint b/.buildkite/lint
--- a/.buildkite/lint
+++ b/.buildkite/lint
@@ -240,7 +240,25 @@ check_commit_authors () {
 
 check_gitlint ()
 {
-	gitlint --commits "$MERGE_BASE..HEAD" || error_exit "Gitlint reported errors"
+	GITLINT_OUTPUT=$(gitlint --commits "$MERGE_BASE..HEAD" 2>&1 | tee /dev/stderr ) || {
+		GITLINT_ERROR=$?
+		if [ -n "${BUILDKITE:-}" ]; then
+			URL_PREFIX=
+			if [[ "${BUILDKITE_REPO:-}" =~ ^(https://|git@)github.com(/|:)([^/]+/[^/.]+) ]]; then
+				URL_PREFIX="https://github.com/${BASH_REMATCH[3]}/commit"
+			fi
+
+			{
+				echo "#### Gitlint Error";
+				sed <<<"$GITLINT_OUTPUT" \
+						-E \
+						-e 's/^([^:]+): ([^:]+): "(.+)"$/- Line \1: *\2*\n```\n\3\n```/g' \
+						-e "s|^Commit ([0-9a-fA-F]+):$|*Commit [\1]($URL_PREFIX\/\1):*|g"
+			} | buildkite-agent annotate --context gitlint --style error
+		fi
+		print_fail "Gitlint exited with errors. See log."
+		exit $GITLINT_ERROR
+	}
 }
 
 
